#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge Upstream For Lean OpenWrt

on:
#   push:
#     branches: 
#       - master
  schedule:
    - cron: 10 */12 * * *
  watch:
    types: started
jobs:

  merge:

    runs-on: ubuntu-latest
    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [19.07,main,rebase-19.07-5.4,rebase-19.07,rebase-main]
    
    steps:

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Load upstream commits
      run: git pull https://github.com/Lienol/openwrt.git ${{matrix.target}} --log --no-commit

    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: ${{matrix.target}}
      run: git push origin $DOWNSTREAM_BRANCH
